spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://139.9.113.221:5432/test?stringtype=unspecified
    #url: jdbc:postgresql://192.168.51.5:5432/test?stringtype=unspecified
    username: pvuser
    password: Pvsu1125
mybatis-plus:
  type-aliases-package: com.pvsoul.demo.entity
  mapper-locations: classpath*:/mapper/**/*.xml
socket-server:
  port: 8090
